apiVersion: batch/v1
kind: Job
metadata:
  name: podscriber-users
  namespace: podscriber
spec:
  template:
    spec:
      containers:
      - name: podscriber-users
        env:
        - name: PYTHONUNBUFFERED
          value: "true"
        envFrom:
        - configMapRef:
            name: podscriber-web
        - secretRef:
            name: podscriber-web
        image: us.gcr.io/oddmark-stage/podscriber-web:latest
        command: ["bash"]
        args: ["-c", "/web/db_scripts/db_create_test_users.sh"]
      restartPolicy: Never
