apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepworker-gpu
  namespace: deepworker
  labels:
    app: deepworker-gpu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepworker-gpu
  template:
    metadata:
      labels:
        app: deepworker-gpu
    spec:
      serviceAccount: deepworker
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-nodepool
                operator: In
                values:
                - gpu
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      containers:
      - name: worker
        image: us.gcr.io/oddmark-stage/podscriber-worker:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: PYTHONUNBUFFERED
          value: "true"
        - name: LC_LANG
          value: C.UTF-8
        - name: LANG
          value: C.UTF-8
        envFrom:
        - configMapRef:
            name: deepworker
        - secretRef:
            name: deepworker
            #TODO: remove this
            optional: true
        command: ["rq"]
        # deepspeech is the queue name
        args: ["worker", "-c", "settings", "deepspeech"]
