apiVersion: apps/v1
kind: Deployment
metadata:
  name: podscriber-web
  namespace: podscriber
  labels:
    app: podscriber-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podscriber-web
  template:
    metadata:
      labels:
        app: podscriber-web
    spec:
      serviceAccount: podscriber
      containers:
      - name: web
        image: us.gcr.io/oddmark-stage/podscriber-web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: PYTHONUNBUFFERED
          value: "true"
        envFrom:
        - configMapRef:
            name: podscriber-web
        - secretRef:
            name: podscriber-web
        #command: ["tail"]
        #args: ["-f", "/dev/null"]
