apiVersion: apps/v1
kind: Deployment
metadata:
  name: podscriber-web
  namespace: podscriber
  labels:
    app: podscriber-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podscriber-web
  template:
    metadata:
      labels:
        app: podscriber-web
    spec:
      serviceAccount: podscriber
      containers:
      - name: web
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        image: us.gcr.io/oddmark-stage/podscriber-web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: PYTHONUNBUFFERED
          value: "true"
        envFrom:
        - configMapRef:
            name: podscriber-web
        - secretRef:
            name: podscriber-web
        #command: ["tail"]
        #args: ["-f", "/dev/null"]
