apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: oddmark-cert
  namespace: istio-system
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretName: oddmark-cert
  issuerRef:
    name: letsencrypt-stage
    kind: ClusterIssuer
  commonName: stage.oddmark.app
  dnsNames:
  - stage.oddmark.app
