apiVersion: v1
kind: Namespace
metadata:
  name: meilisearch

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: meilisearch
  namespace: meilisearch
spec:
  selector:
    matchLabels:
      app: meilisearch
  serviceName: "meilisearch"
  replicas: 1
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: meilisearch
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        image: getmeili/meilisearch:v0.12.0
        ports:
        - containerPort: 7700
          name: web
        volumeMounts:
        - name: meilisearch
          mountPath: /data.ms
  volumeClaimTemplates:
  - metadata:
      name: meilisearch
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 10Gi

---

apiVersion: v1
kind: Service
metadata:
  name: meilisearch
spec:
  selector:
    app: meilisearch
  ports:
    - name: http
      protocol: TCP
      port: 7700
      targetPort: 7700
