apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  generation: 1
  name: podscriber
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/applications/podscriber
spec:
  destination:
    namespace: podscriber
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/services
    repoURL: https://github.com/DoubleGin/infrastructure.git
    targetRevision: HEAD
status:
  health:
    status: Missing
  observedAt: "2020-06-26T06:13:20Z"
  operationState:
    finishedAt: "2020-06-26T03:17:26Z"
    message: one or more synchronization tasks are not valid
    operation:
      initiatedBy:
        username: admin
      sync:
        revision: d089201ee4ec291100666d9c56aafe2913a90075
        syncStrategy:
          hook: {}
    phase: Failed
    startedAt: "2020-06-26T03:17:26Z"
    syncResult:
      resources:
      - group: networking.istio.io
        kind: VirtualService
        message: the server could not find the requested resource
        name: podscriber-web
        namespace: istio-system
        status: SyncFailed
        syncPhase: Sync
        version: v1beta1
      revision: d089201ee4ec291100666d9c56aafe2913a90075
      source:
        path: k8s/services
        repoURL: https://github.com/DoubleGin/infrastructure.git
        targetRevision: HEAD
  reconciledAt: "2020-06-26T06:13:20Z"
  resources:
  - health:
      status: Missing
    kind: Service
    name: podscriber-web
    namespace: podscriber
    status: OutOfSync
    version: v1
  - group: networking.istio.io
    health:
      status: Missing
    kind: VirtualService
    name: podscriber-web
    namespace: istio-system
    status: OutOfSync
    version: v1beta1
  - group: apps
    health:
      status: Missing
    kind: Deployment
    name: podscriber-web
    namespace: podscriber
    status: OutOfSync
    version: v1
  - group: apps
    health:
      status: Missing
    kind: Deployment
    name: podscriber-worker
    namespace: podscriber
    status: OutOfSync
    version: v1
  sourceType: Directory
  summary: {}
  sync:
    comparedTo:
      destination:
        namespace: podscriber
        server: https://kubernetes.default.svc
      source:
        path: k8s/services
        repoURL: https://github.com/DoubleGin/infrastructure.git
        targetRevision: HEAD
    revision: 878468607b0d9d05e0f0f95a7c44f736ab7d7a8c
    status: OutOfSync
