apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argocd
  namespace: istio-system
spec:
  hosts:
  - stage.oddmark.app
  gateways:
  - oddmark-gateway
  http:
  - match:
    - uri: 
        prefix: /argo/
    route:
    - destination:
        host: argocd-server.argocd.svc.cluster.local
        port:
          number: 80

