apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/cert-manager
    repoURL: https://github.com/DoubleGin/infrastructure.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
