apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/external-dns
    repoURL: https://github.com/DoubleGin/infrastructure.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
