apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
    kind: MutatingWebhookConfiguration
  - group: admissionregistration.k8s.io
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
    - /webhooks/0/failurePolicy
    kind: ValidatingWebhookConfiguration
  project: default
  source:
    path: k8s/istio
    repoURL: https://github.com/DoubleGin/infrastructure.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
